python trainer/train_trans_generator.py \
--order C-M \
--dataset_name GDSS_com \
--max_epochs 500 \
--check_sample_every_n_epoch 501 \
--replicate 0 \
--max_len 48 \
--wandb_on online \
--string_type group-red \
--lr 0.001 \
--batch_size 128 \
--num_samples 128 \
--sample_batch_size 128 \
--tree_pos \
--pos_type emb \
--dropout 0.1 \
--input_dropout 0 \
--k 2