python trainer/train_trans_generator.py \
--order C-M \
--dataset_name GDSS_grid \
--max_epochs 500 \
--check_sample_every_n_epoch 501 \
--replicate 0 \
--max_len 706 \
--wandb_on online \
--string_type group-red \
--lr 0.0005 \
--batch_size 8 \
--num_samples 200 \
--tree_pos \
--pos_type emb \
--dropout 0.1 \
--input_dropout 0 \
--sample_batch_size 50 \
--k 2